nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: 9
enableTelemetry: false
nmHoistingLimits: workspaces
enableInlineBuilds: true
nmMode: hardlinks-local
preferInteractive: false
enableTimers: false
