#:schema node_modules/wrangler/config-schema.json
name = "aminals-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build:all && npm run build:cf"

[env.production]
NODE_ENV = "production"