schema {
  query: Query
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

scalar BigInt

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Meta {
  status: JSON
}

type Query {
  factory(id: String!): factory
  factorys(where: factoryFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): factoryPage!
  aminal(id: String!): aminal
  aminals(where: aminalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): aminalPage!
  user(id: String!): user
  users(where: userFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): userPage!
  relationship(id: String!): relationship
  relationships(where: relationshipFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): relationshipPage!
  geneNFT(id: String!): geneNFT
  geneNFTs(where: geneNFTFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneNFTPage!
  geneAuction(id: String!): geneAuction
  geneAuctions(where: geneAuctionFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneAuctionPage!
  geneProposal(id: String!): geneProposal
  geneProposals(where: geneProposalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneProposalPage!
  geneVote(id: String!): geneVote
  geneVotes(where: geneVoteFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneVotePage!
  geneCreatorPayout(id: String!): geneCreatorPayout
  geneCreatorPayouts(where: geneCreatorPayoutFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneCreatorPayoutPage!
  feedEvent(id: String!): feedEvent
  feedEvents(where: feedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): feedEventPage!
  skillUsedEvent(id: String!): skillUsedEvent
  skillUsedEvents(where: skillUsedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): skillUsedEventPage!
  _meta: Meta
}

type factory {
  id: String!
  totalAminals: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  aminals(where: aminalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): aminalPage
}

type aminalPage {
  items: [aminal!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type aminal {
  id: String!
  contractAddress: String!
  aminalIndex: BigInt!
  factoryId: String!
  parentOneId: String
  parentTwoId: String
  auctionId: BigInt
  traits: [BigInt!]!
  energy: BigInt!
  totalLove: BigInt!
  ethBalance: BigInt!
  tokenURI: String
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  factory: factory
  parentOne: aminal
  parentTwo: aminal
  childrenAsParentOne(where: aminalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): aminalPage
  childrenAsParentTwo(where: aminalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): aminalPage
  lovers(where: relationshipFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): relationshipPage
  feeds(where: feedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): feedEventPage
  skillsUsed(where: skillUsedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): skillUsedEventPage
}

input aminalFilter {
  AND: [aminalFilter]
  OR: [aminalFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  contractAddress: String
  contractAddress_not: String
  contractAddress_in: [String]
  contractAddress_not_in: [String]
  contractAddress_contains: String
  contractAddress_not_contains: String
  contractAddress_starts_with: String
  contractAddress_ends_with: String
  contractAddress_not_starts_with: String
  contractAddress_not_ends_with: String
  aminalIndex: BigInt
  aminalIndex_not: BigInt
  aminalIndex_in: [BigInt]
  aminalIndex_not_in: [BigInt]
  aminalIndex_gt: BigInt
  aminalIndex_lt: BigInt
  aminalIndex_gte: BigInt
  aminalIndex_lte: BigInt
  factoryId: String
  factoryId_not: String
  factoryId_in: [String]
  factoryId_not_in: [String]
  factoryId_contains: String
  factoryId_not_contains: String
  factoryId_starts_with: String
  factoryId_ends_with: String
  factoryId_not_starts_with: String
  factoryId_not_ends_with: String
  parentOneId: String
  parentOneId_not: String
  parentOneId_in: [String]
  parentOneId_not_in: [String]
  parentOneId_contains: String
  parentOneId_not_contains: String
  parentOneId_starts_with: String
  parentOneId_ends_with: String
  parentOneId_not_starts_with: String
  parentOneId_not_ends_with: String
  parentTwoId: String
  parentTwoId_not: String
  parentTwoId_in: [String]
  parentTwoId_not_in: [String]
  parentTwoId_contains: String
  parentTwoId_not_contains: String
  parentTwoId_starts_with: String
  parentTwoId_ends_with: String
  parentTwoId_not_starts_with: String
  parentTwoId_not_ends_with: String
  auctionId: BigInt
  auctionId_not: BigInt
  auctionId_in: [BigInt]
  auctionId_not_in: [BigInt]
  auctionId_gt: BigInt
  auctionId_lt: BigInt
  auctionId_gte: BigInt
  auctionId_lte: BigInt
  traits: [BigInt]
  traits_not: [BigInt]
  traits_has: BigInt
  traits_not_has: BigInt
  energy: BigInt
  energy_not: BigInt
  energy_in: [BigInt]
  energy_not_in: [BigInt]
  energy_gt: BigInt
  energy_lt: BigInt
  energy_gte: BigInt
  energy_lte: BigInt
  totalLove: BigInt
  totalLove_not: BigInt
  totalLove_in: [BigInt]
  totalLove_not_in: [BigInt]
  totalLove_gt: BigInt
  totalLove_lt: BigInt
  totalLove_gte: BigInt
  totalLove_lte: BigInt
  ethBalance: BigInt
  ethBalance_not: BigInt
  ethBalance_in: [BigInt]
  ethBalance_not_in: [BigInt]
  ethBalance_gt: BigInt
  ethBalance_lt: BigInt
  ethBalance_gte: BigInt
  ethBalance_lte: BigInt
  tokenURI: String
  tokenURI_not: String
  tokenURI_in: [String]
  tokenURI_not_in: [String]
  tokenURI_contains: String
  tokenURI_not_contains: String
  tokenURI_starts_with: String
  tokenURI_ends_with: String
  tokenURI_not_starts_with: String
  tokenURI_not_ends_with: String
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type relationshipPage {
  items: [relationship!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type relationship {
  id: String!
  userId: String!
  aminalId: String!
  love: BigInt!
  user: user
  aminal: aminal
}

type user {
  id: String!
  address: String!
  lovers(where: relationshipFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): relationshipPage
  genesCreated(where: geneNFTFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneNFTPage
  genesOwned(where: geneNFTFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneNFTPage
  geneVotes(where: geneVoteFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneVotePage
  proposedGenes(where: geneProposalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneProposalPage
  receivedPayouts(where: geneCreatorPayoutFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneCreatorPayoutPage
  feedEvents(where: feedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): feedEventPage
  skillEvents(where: skillUsedEventFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): skillUsedEventPage
}

input relationshipFilter {
  AND: [relationshipFilter]
  OR: [relationshipFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  userId: String
  userId_not: String
  userId_in: [String]
  userId_not_in: [String]
  userId_contains: String
  userId_not_contains: String
  userId_starts_with: String
  userId_ends_with: String
  userId_not_starts_with: String
  userId_not_ends_with: String
  aminalId: String
  aminalId_not: String
  aminalId_in: [String]
  aminalId_not_in: [String]
  aminalId_contains: String
  aminalId_not_contains: String
  aminalId_starts_with: String
  aminalId_ends_with: String
  aminalId_not_starts_with: String
  aminalId_not_ends_with: String
  love: BigInt
  love_not: BigInt
  love_in: [BigInt]
  love_not_in: [BigInt]
  love_gt: BigInt
  love_lt: BigInt
  love_gte: BigInt
  love_lte: BigInt
}

type geneNFTPage {
  items: [geneNFT!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type geneNFT {
  id: String!
  tokenId: BigInt!
  traitType: Int!
  ownerId: String!
  creatorId: String!
  svg: String
  name: String
  description: String
  totalEarnings: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  owner: user
  creator: user
  proposals(where: geneProposalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneProposalPage
  payouts(where: geneCreatorPayoutFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneCreatorPayoutPage
}

type geneProposalPage {
  items: [geneProposal!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type geneProposal {
  id: String!
  auctionId: String!
  geneNFTId: String!
  traitType: Int!
  proposerId: String!
  loveVotes: BigInt!
  removeVotes: BigInt!
  removed: Boolean!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  auction: geneAuction
  geneNFT: geneNFT
  proposer: user
  votes(where: geneVoteFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneVotePage
}

type geneAuction {
  id: String!
  auctionId: BigInt!
  aminalOneId: String!
  aminalTwoId: String!
  totalLove: BigInt!
  parentGeneIds: [BigInt!]!
  finished: Boolean!
  childAminalId: String
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  aminalOne: aminal
  aminalTwo: aminal
  childAminal: aminal
  proposals(where: geneProposalFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneProposalPage
  votes(where: geneVoteFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneVotePage
  payouts(where: geneCreatorPayoutFilter, orderBy: String, orderDirection: String, before: String, after: String, limit: Int): geneCreatorPayoutPage
}

input geneProposalFilter {
  AND: [geneProposalFilter]
  OR: [geneProposalFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  auctionId: String
  auctionId_not: String
  auctionId_in: [String]
  auctionId_not_in: [String]
  auctionId_contains: String
  auctionId_not_contains: String
  auctionId_starts_with: String
  auctionId_ends_with: String
  auctionId_not_starts_with: String
  auctionId_not_ends_with: String
  geneNFTId: String
  geneNFTId_not: String
  geneNFTId_in: [String]
  geneNFTId_not_in: [String]
  geneNFTId_contains: String
  geneNFTId_not_contains: String
  geneNFTId_starts_with: String
  geneNFTId_ends_with: String
  geneNFTId_not_starts_with: String
  geneNFTId_not_ends_with: String
  traitType: Int
  traitType_not: Int
  traitType_in: [Int]
  traitType_not_in: [Int]
  traitType_gt: Int
  traitType_lt: Int
  traitType_gte: Int
  traitType_lte: Int
  proposerId: String
  proposerId_not: String
  proposerId_in: [String]
  proposerId_not_in: [String]
  proposerId_contains: String
  proposerId_not_contains: String
  proposerId_starts_with: String
  proposerId_ends_with: String
  proposerId_not_starts_with: String
  proposerId_not_ends_with: String
  loveVotes: BigInt
  loveVotes_not: BigInt
  loveVotes_in: [BigInt]
  loveVotes_not_in: [BigInt]
  loveVotes_gt: BigInt
  loveVotes_lt: BigInt
  loveVotes_gte: BigInt
  loveVotes_lte: BigInt
  removeVotes: BigInt
  removeVotes_not: BigInt
  removeVotes_in: [BigInt]
  removeVotes_not_in: [BigInt]
  removeVotes_gt: BigInt
  removeVotes_lt: BigInt
  removeVotes_gte: BigInt
  removeVotes_lte: BigInt
  removed: Boolean
  removed_not: Boolean
  removed_in: [Boolean]
  removed_not_in: [Boolean]
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type geneVotePage {
  items: [geneVote!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type geneVote {
  id: String!
  auctionId: String!
  proposalId: String!
  voterId: String!
  isRemoveVote: Boolean!
  loveAmount: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  auction: geneAuction
  proposal: geneProposal
  voter: user
}

input geneVoteFilter {
  AND: [geneVoteFilter]
  OR: [geneVoteFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  auctionId: String
  auctionId_not: String
  auctionId_in: [String]
  auctionId_not_in: [String]
  auctionId_contains: String
  auctionId_not_contains: String
  auctionId_starts_with: String
  auctionId_ends_with: String
  auctionId_not_starts_with: String
  auctionId_not_ends_with: String
  proposalId: String
  proposalId_not: String
  proposalId_in: [String]
  proposalId_not_in: [String]
  proposalId_contains: String
  proposalId_not_contains: String
  proposalId_starts_with: String
  proposalId_ends_with: String
  proposalId_not_starts_with: String
  proposalId_not_ends_with: String
  voterId: String
  voterId_not: String
  voterId_in: [String]
  voterId_not_in: [String]
  voterId_contains: String
  voterId_not_contains: String
  voterId_starts_with: String
  voterId_ends_with: String
  voterId_not_starts_with: String
  voterId_not_ends_with: String
  isRemoveVote: Boolean
  isRemoveVote_not: Boolean
  isRemoveVote_in: [Boolean]
  isRemoveVote_not_in: [Boolean]
  loveAmount: BigInt
  loveAmount_not: BigInt
  loveAmount_in: [BigInt]
  loveAmount_not_in: [BigInt]
  loveAmount_gt: BigInt
  loveAmount_lt: BigInt
  loveAmount_gte: BigInt
  loveAmount_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type geneCreatorPayoutPage {
  items: [geneCreatorPayout!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type geneCreatorPayout {
  id: String!
  auctionId: String!
  geneNFTId: String!
  creatorId: String!
  amount: BigInt!
  auctionIdRaw: BigInt!
  geneIdRaw: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  auction: geneAuction
  geneNFT: geneNFT
  creator: user
}

input geneCreatorPayoutFilter {
  AND: [geneCreatorPayoutFilter]
  OR: [geneCreatorPayoutFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  auctionId: String
  auctionId_not: String
  auctionId_in: [String]
  auctionId_not_in: [String]
  auctionId_contains: String
  auctionId_not_contains: String
  auctionId_starts_with: String
  auctionId_ends_with: String
  auctionId_not_starts_with: String
  auctionId_not_ends_with: String
  geneNFTId: String
  geneNFTId_not: String
  geneNFTId_in: [String]
  geneNFTId_not_in: [String]
  geneNFTId_contains: String
  geneNFTId_not_contains: String
  geneNFTId_starts_with: String
  geneNFTId_ends_with: String
  geneNFTId_not_starts_with: String
  geneNFTId_not_ends_with: String
  creatorId: String
  creatorId_not: String
  creatorId_in: [String]
  creatorId_not_in: [String]
  creatorId_contains: String
  creatorId_not_contains: String
  creatorId_starts_with: String
  creatorId_ends_with: String
  creatorId_not_starts_with: String
  creatorId_not_ends_with: String
  amount: BigInt
  amount_not: BigInt
  amount_in: [BigInt]
  amount_not_in: [BigInt]
  amount_gt: BigInt
  amount_lt: BigInt
  amount_gte: BigInt
  amount_lte: BigInt
  auctionIdRaw: BigInt
  auctionIdRaw_not: BigInt
  auctionIdRaw_in: [BigInt]
  auctionIdRaw_not_in: [BigInt]
  auctionIdRaw_gt: BigInt
  auctionIdRaw_lt: BigInt
  auctionIdRaw_gte: BigInt
  auctionIdRaw_lte: BigInt
  geneIdRaw: BigInt
  geneIdRaw_not: BigInt
  geneIdRaw_in: [BigInt]
  geneIdRaw_not_in: [BigInt]
  geneIdRaw_gt: BigInt
  geneIdRaw_lt: BigInt
  geneIdRaw_gte: BigInt
  geneIdRaw_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

input geneNFTFilter {
  AND: [geneNFTFilter]
  OR: [geneNFTFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  tokenId: BigInt
  tokenId_not: BigInt
  tokenId_in: [BigInt]
  tokenId_not_in: [BigInt]
  tokenId_gt: BigInt
  tokenId_lt: BigInt
  tokenId_gte: BigInt
  tokenId_lte: BigInt
  traitType: Int
  traitType_not: Int
  traitType_in: [Int]
  traitType_not_in: [Int]
  traitType_gt: Int
  traitType_lt: Int
  traitType_gte: Int
  traitType_lte: Int
  ownerId: String
  ownerId_not: String
  ownerId_in: [String]
  ownerId_not_in: [String]
  ownerId_contains: String
  ownerId_not_contains: String
  ownerId_starts_with: String
  ownerId_ends_with: String
  ownerId_not_starts_with: String
  ownerId_not_ends_with: String
  creatorId: String
  creatorId_not: String
  creatorId_in: [String]
  creatorId_not_in: [String]
  creatorId_contains: String
  creatorId_not_contains: String
  creatorId_starts_with: String
  creatorId_ends_with: String
  creatorId_not_starts_with: String
  creatorId_not_ends_with: String
  svg: String
  svg_not: String
  svg_in: [String]
  svg_not_in: [String]
  svg_contains: String
  svg_not_contains: String
  svg_starts_with: String
  svg_ends_with: String
  svg_not_starts_with: String
  svg_not_ends_with: String
  name: String
  name_not: String
  name_in: [String]
  name_not_in: [String]
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_ends_with: String
  name_not_starts_with: String
  name_not_ends_with: String
  description: String
  description_not: String
  description_in: [String]
  description_not_in: [String]
  description_contains: String
  description_not_contains: String
  description_starts_with: String
  description_ends_with: String
  description_not_starts_with: String
  description_not_ends_with: String
  totalEarnings: BigInt
  totalEarnings_not: BigInt
  totalEarnings_in: [BigInt]
  totalEarnings_not_in: [BigInt]
  totalEarnings_gt: BigInt
  totalEarnings_lt: BigInt
  totalEarnings_gte: BigInt
  totalEarnings_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type feedEventPage {
  items: [feedEvent!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type feedEvent {
  id: String!
  aminalId: String!
  senderId: String!
  amount: BigInt!
  love: BigInt!
  totalLove: BigInt!
  energy: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  aminal: aminal
  sender: user
}

input feedEventFilter {
  AND: [feedEventFilter]
  OR: [feedEventFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  aminalId: String
  aminalId_not: String
  aminalId_in: [String]
  aminalId_not_in: [String]
  aminalId_contains: String
  aminalId_not_contains: String
  aminalId_starts_with: String
  aminalId_ends_with: String
  aminalId_not_starts_with: String
  aminalId_not_ends_with: String
  senderId: String
  senderId_not: String
  senderId_in: [String]
  senderId_not_in: [String]
  senderId_contains: String
  senderId_not_contains: String
  senderId_starts_with: String
  senderId_ends_with: String
  senderId_not_starts_with: String
  senderId_not_ends_with: String
  amount: BigInt
  amount_not: BigInt
  amount_in: [BigInt]
  amount_not_in: [BigInt]
  amount_gt: BigInt
  amount_lt: BigInt
  amount_gte: BigInt
  amount_lte: BigInt
  love: BigInt
  love_not: BigInt
  love_in: [BigInt]
  love_not_in: [BigInt]
  love_gt: BigInt
  love_lt: BigInt
  love_gte: BigInt
  love_lte: BigInt
  totalLove: BigInt
  totalLove_not: BigInt
  totalLove_in: [BigInt]
  totalLove_not_in: [BigInt]
  totalLove_gt: BigInt
  totalLove_lt: BigInt
  totalLove_gte: BigInt
  totalLove_lte: BigInt
  energy: BigInt
  energy_not: BigInt
  energy_in: [BigInt]
  energy_not_in: [BigInt]
  energy_gt: BigInt
  energy_lt: BigInt
  energy_gte: BigInt
  energy_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type skillUsedEventPage {
  items: [skillUsedEvent!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type skillUsedEvent {
  id: String!
  aminalId: String!
  callerId: String!
  skillAddress: String!
  selector: String!
  newEnergy: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
  aminal: aminal
  caller: user
}

input skillUsedEventFilter {
  AND: [skillUsedEventFilter]
  OR: [skillUsedEventFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  aminalId: String
  aminalId_not: String
  aminalId_in: [String]
  aminalId_not_in: [String]
  aminalId_contains: String
  aminalId_not_contains: String
  aminalId_starts_with: String
  aminalId_ends_with: String
  aminalId_not_starts_with: String
  aminalId_not_ends_with: String
  callerId: String
  callerId_not: String
  callerId_in: [String]
  callerId_not_in: [String]
  callerId_contains: String
  callerId_not_contains: String
  callerId_starts_with: String
  callerId_ends_with: String
  callerId_not_starts_with: String
  callerId_not_ends_with: String
  skillAddress: String
  skillAddress_not: String
  skillAddress_in: [String]
  skillAddress_not_in: [String]
  skillAddress_contains: String
  skillAddress_not_contains: String
  skillAddress_starts_with: String
  skillAddress_ends_with: String
  skillAddress_not_starts_with: String
  skillAddress_not_ends_with: String
  selector: String
  selector_not: String
  selector_in: [String]
  selector_not_in: [String]
  selector_contains: String
  selector_not_contains: String
  selector_starts_with: String
  selector_ends_with: String
  selector_not_starts_with: String
  selector_not_ends_with: String
  newEnergy: BigInt
  newEnergy_not: BigInt
  newEnergy_in: [BigInt]
  newEnergy_not_in: [BigInt]
  newEnergy_gt: BigInt
  newEnergy_lt: BigInt
  newEnergy_gte: BigInt
  newEnergy_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type factoryPage {
  items: [factory!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

input factoryFilter {
  AND: [factoryFilter]
  OR: [factoryFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  totalAminals: BigInt
  totalAminals_not: BigInt
  totalAminals_in: [BigInt]
  totalAminals_not_in: [BigInt]
  totalAminals_gt: BigInt
  totalAminals_lt: BigInt
  totalAminals_gte: BigInt
  totalAminals_lte: BigInt
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}

type userPage {
  items: [user!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

input userFilter {
  AND: [userFilter]
  OR: [userFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  address: String
  address_not: String
  address_in: [String]
  address_not_in: [String]
  address_contains: String
  address_not_contains: String
  address_starts_with: String
  address_ends_with: String
  address_not_starts_with: String
  address_not_ends_with: String
}

type geneAuctionPage {
  items: [geneAuction!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

input geneAuctionFilter {
  AND: [geneAuctionFilter]
  OR: [geneAuctionFilter]
  id: String
  id_not: String
  id_in: [String]
  id_not_in: [String]
  id_contains: String
  id_not_contains: String
  id_starts_with: String
  id_ends_with: String
  id_not_starts_with: String
  id_not_ends_with: String
  auctionId: BigInt
  auctionId_not: BigInt
  auctionId_in: [BigInt]
  auctionId_not_in: [BigInt]
  auctionId_gt: BigInt
  auctionId_lt: BigInt
  auctionId_gte: BigInt
  auctionId_lte: BigInt
  aminalOneId: String
  aminalOneId_not: String
  aminalOneId_in: [String]
  aminalOneId_not_in: [String]
  aminalOneId_contains: String
  aminalOneId_not_contains: String
  aminalOneId_starts_with: String
  aminalOneId_ends_with: String
  aminalOneId_not_starts_with: String
  aminalOneId_not_ends_with: String
  aminalTwoId: String
  aminalTwoId_not: String
  aminalTwoId_in: [String]
  aminalTwoId_not_in: [String]
  aminalTwoId_contains: String
  aminalTwoId_not_contains: String
  aminalTwoId_starts_with: String
  aminalTwoId_ends_with: String
  aminalTwoId_not_starts_with: String
  aminalTwoId_not_ends_with: String
  totalLove: BigInt
  totalLove_not: BigInt
  totalLove_in: [BigInt]
  totalLove_not_in: [BigInt]
  totalLove_gt: BigInt
  totalLove_lt: BigInt
  totalLove_gte: BigInt
  totalLove_lte: BigInt
  parentGeneIds: [BigInt]
  parentGeneIds_not: [BigInt]
  parentGeneIds_has: BigInt
  parentGeneIds_not_has: BigInt
  finished: Boolean
  finished_not: Boolean
  finished_in: [Boolean]
  finished_not_in: [Boolean]
  childAminalId: String
  childAminalId_not: String
  childAminalId_in: [String]
  childAminalId_not_in: [String]
  childAminalId_contains: String
  childAminalId_not_contains: String
  childAminalId_starts_with: String
  childAminalId_ends_with: String
  childAminalId_not_starts_with: String
  childAminalId_not_ends_with: String
  blockNumber: BigInt
  blockNumber_not: BigInt
  blockNumber_in: [BigInt]
  blockNumber_not_in: [BigInt]
  blockNumber_gt: BigInt
  blockNumber_lt: BigInt
  blockNumber_gte: BigInt
  blockNumber_lte: BigInt
  blockTimestamp: BigInt
  blockTimestamp_not: BigInt
  blockTimestamp_in: [BigInt]
  blockTimestamp_not_in: [BigInt]
  blockTimestamp_gt: BigInt
  blockTimestamp_lt: BigInt
  blockTimestamp_gte: BigInt
  blockTimestamp_lte: BigInt
  transactionHash: String
  transactionHash_not: String
  transactionHash_in: [String]
  transactionHash_not_in: [String]
  transactionHash_contains: String
  transactionHash_not_contains: String
  transactionHash_starts_with: String
  transactionHash_ends_with: String
  transactionHash_not_starts_with: String
  transactionHash_not_ends_with: String
}