query GeneNftsList {
  geneNFTs(orderBy: "tokenId", orderDirection: "asc", limit: 100) {
    items {
      id
      tokenId
      traitType
      name
      description
      svg
      owner {
        id
        address
      }
      creator {
        id
        address
      }
      totalEarnings
      proposals(limit: 100) {
        items {
          id
          auction {
            id
            aminalOne {
              id
              contractAddress
              aminalIndex
              tokenURI
              energy
              totalLove
            }
            aminalTwo {
              id
              contractAddress
              aminalIndex
              tokenURI
              energy
              totalLove
            }
          }
        }
      }
      payouts(limit: 100, orderBy: "blockTimestamp", orderDirection: "desc") {
        items {
          id
          amount
          auctionId
          blockTimestamp
          auction {
            id
            auctionId
          }
        }
      }
      blockTimestamp
    }
  }
}

query GeneNftById($id: String!) {
  geneNFT(id: $id) {
    id
    tokenId
    traitType
    name
    description
    svg
    owner {
      id
      address
    }
    creator {
      id
      address
    }
    totalEarnings
    proposals(limit: 100) {
      items {
        id
        auction {
          id
          aminalOne {
            id
            contractAddress
            aminalIndex
            tokenURI
            energy
            totalLove
          }
          aminalTwo {
            id
            contractAddress
            aminalIndex
            tokenURI
            energy
            totalLove
          }
        }
      }
    }
    payouts(limit: 100, orderBy: "blockTimestamp", orderDirection: "desc") {
      items {
        id
        amount
        auctionId
        blockTimestamp
        auction {
          id
          auctionId
        }
      }
    }
    blockTimestamp
  }
}

query GenesByTraitType($traitType: Int!) {
  geneNFTs(
    where: { traitType: $traitType }
    orderBy: "tokenId"
    orderDirection: "asc"
    limit: 100
  ) {
    items {
      id
      tokenId
      traitType
      name
      description
      svg
      owner {
        id
        address
      }
      creator {
        id
        address
      }
      totalEarnings
      proposals(limit: 100) {
        items {
          id
          auction {
            id
            aminalOne {
              id
              contractAddress
              aminalIndex
              tokenURI
              energy
              totalLove
            }
            aminalTwo {
              id
              contractAddress
              aminalIndex
              tokenURI
              energy
              totalLove
            }
          }
        }
      }
      payouts(limit: 100, orderBy: "blockTimestamp", orderDirection: "desc") {
        items {
          id
          amount
          auctionId
          blockTimestamp
          auction {
            id
            auctionId
          }
        }
      }
      blockTimestamp
    }
  }
}

query GenesByIds($ids: [BigInt!]!) {
  geneNFTs(where: { tokenId_in: $ids }, limit: 100) {
    items {
      id
      tokenId
      traitType
      name
      description
      svg
    }
  }
}
