query SkillUsedList($first: Int = 100) {
  skillUsedEvents(
    limit: $first
    orderBy: "blockTimestamp"
    orderDirection: "desc"
  ) {
    items {
      id
      aminal {
        id
      }
      caller {
        id
        address
      }
      skillAddress
      selector
      newEnergy
      blockTimestamp
    }
  }
}

query SkillUsedByAminal($aminalId: String!) {
  skillUsedEvents(
    where: { aminalId: $aminalId }
    orderBy: "blockTimestamp"
    orderDirection: "desc"
    limit: 100
  ) {
    items {
      id
      caller {
        id
        address
      }
      skillAddress
      selector
      newEnergy
      blockTimestamp
    }
  }
}

query SkillUsedBySkill($skillAddress: String!) {
  skillUsedEvents(
    where: { skillAddress: $skillAddress }
    orderBy: "blockTimestamp"
    orderDirection: "desc"
    limit: 100
  ) {
    items {
      id
      aminal {
        id
      }
      caller {
        id
        address
      }
      selector
      newEnergy
      blockTimestamp
    }
  }
}
