query UserProfile($address: String!) {
  user(id: $address) {
    id
    address
    lovers(limit: 100) {
      items {
        id
        aminal {
          id
          contractAddress
          tokenURI
          totalLove
          energy
          ethBalance
          blockTimestamp
        }
        love
      }
    }
    genesCreated(limit: 100) {
      items {
        id
        tokenId
        traitType
        name
        description
        svg
        totalEarnings
        blockTimestamp
        payouts(limit: 100) {
          items {
            id
            amount
            auctionId
            blockTimestamp
          }
        }
      }
    }
    genesOwned(limit: 100) {
      items {
        id
        tokenId
        traitType
        name
        description
        svg
        totalEarnings
        blockTimestamp
        creator {
          id
          address
        }
      }
    }
    geneVotes(limit: 100) {
      items {
        id
        auction {
          id
          auctionId
          aminalOne {
            id
            contractAddress
            tokenURI
          }
          aminalTwo {
            id
            contractAddress
            tokenURI
          }
        }
        proposal {
          id
          geneNFT {
            id
            tokenId
            name
            traitType
          }
        }
        isRemoveVote
        loveAmount
        blockTimestamp
      }
    }
  }
}

query UserEarnings($address: String!) {
  user(id: $address) {
    id
    address
    genesCreated(limit: 100) {
      items {
        id
        tokenId
        name
        traitType
        totalEarnings
        payouts(limit: 100, orderBy: "blockTimestamp", orderDirection: "desc") {
          items {
            id
            amount
            auctionId
            blockTimestamp
            auction {
              id
              auctionId
              aminalOne {
                id
                contractAddress
                tokenURI
              }
              aminalTwo {
                id
                contractAddress
                tokenURI
              }
            }
          }
        }
      }
    }
  }
}

query UserActivity($address: String!) {
  user(id: $address) {
    id
    address
    lovers(orderBy: "love", orderDirection: "desc", limit: 10) {
      items {
        id
        aminal {
          id
          contractAddress
          tokenURI
          totalLove
        }
        love
      }
    }
    geneVotes(orderBy: "blockTimestamp", orderDirection: "desc", limit: 10) {
      items {
        id
        auction {
          id
          auctionId
        }
        proposal {
          id
          geneNFT {
            id
            tokenId
            name
            traitType
          }
        }
        isRemoveVote
        loveAmount
        blockTimestamp
      }
    }
  }
}
